req.on('error', (err) => {
  log(`request encountered an error: ${err}`)
})
